export type NoteEntityType = "Contact" | "SalesInvoice";
export type ToDoType =
    'sales_invoice_due'
    | 'purchase_invoice_due'
    | 'general_document_reminder'
    | 'general_document_due'
    | 'new_document_awaiting_processing'
    | 'new_financial_mutation_awaiting_processing'
    | 'financial_mutations_not_updated'
    | 'sales_invoice_payment_not_linked_to_financial_mutation'
    | 'document_payment_not_linked_to_financial_mutation'
    | 'sales_invoice_awaiting_payment_batch'
    | 'export_sales_invoices_ready'
    | 'export_documents_ready'
    | 'export_contacts_ready'
    | 'import_contacts_ready'
    | 'recurring_sales_invoice_auto_send_failed'
    | 'sales_invoice_scheduled_sending_failed'
    | 'sales_invoice_reminder_sending_failed'
    | 'sales_invoice_becoming_due'
    | 'sales_invoice_collecting_failed'
    | 'estimate_due'
    | 'export_estimates_ready'
    | 'sales_invoice_email_delivery_failed'
    | 'sales_invoice_email_marked_as_spam'
    | 'estimate_email_delivery_failed'
    | 'estimate_email_marked_as_spam'
    | 'purchase_invoice_invalid_ubl'
    | 'sales_invoice_unprintable'
    | 'estimate_unprintable'
    | 'auditfile_ready'
    | 'import_financial_statement_finished'
    | 'recurring_sales_invoice_auto_send_skipped_import_wizard'
    | 'ledger_account_report_export_ready'
    | 'recurring_sales_invoice_failed_deleted_contact'
    | 'recurring_sales_invoice_create_invoice_failed'
    | 'sales_invoice_simplerinvoicing_delivery_failed_unroutable'
    | 'purchase_invoice_received_simplerinvoicing'
    | 'sales_invoice_simplerinvoicing_delivery_error'
    | 'purchase_transaction_expired'
    | 'sales_invoice_si_delivery_failed_contact_unreachable'
    | 'sales_invoice_si_delivery_failed_deactivated'
    | 'sales_invoice_si_delivery_failed_identity_unverified'
    | 'sales_invoice_si_delivery_failed_length_exceeded'
    | 'recurring_document_stopped_by_contact_delete'
    | 'sales_invoice_email_previously_bounced'
    | 'estimate_email_previously_bounced'
    | 'email_domain_invalidated'
    | 'external_sales_invoice_invalid_ubl'
    | 'sales_invoice_email_invalid_address'
    | 'estimate_email_invalid_address'
    | 'gateway_connection_terminated'
    | 'sales_invoice_email_payload_too_large'
    | 'estimate_email_payload_too_large'
    | 'ponto_organization_not_activated'
    | 'ponto_financial_institution_deprecated'
    | 'contact_email_delivery_failed'
    | 'contact_email_marked_as_spam'
    | 'contact_email_previously_bounced'
    | 'contact_email_invalid_address'
    | 'contact_email_payload_too_large'
    | 'sales_invoice_scheduling_failed_due_to_payment_information'
    | 'sales_invoice_collecting_failed_missing_subscription'
    | 'sales_invoice_si_delivery_failed_ubl_validation_failed'
    | 'sales_invoice_email_sender_limit'
    | 'estimate_email_sender_limit'
    | 'contact_email_sender_limit'
    | 'sales_invoice_email_invalid_attachment'
    | 'estimate_email_invalid_attachment'
    | 'contact_email_invalid_attachment'
    | 'sales_invoice_collecting_failed_monthly_limit_exceeded'
    | 'adyen_verification_error'
    | 'contact_email_not_present'
    | 'financial_mutation_failed'
    | 'sales_invoice_si_delivery_failed_invalid_sender'
    | 'sales_invoice_tax_number_invalid'
    | 'payment_transaction_no_positive_payment'
    | 'financial_mutation_payment_locked';

export interface AddNoteOptions {
    /** Text for the note or to-do. */
    note: string
    /** If `true`, the note is a to-do. */
    todo?: boolean
    /** Assign to-do to user. Should be a valid {@link User.id}. If {@link assignee_id} is provided, the note will be a to-do. */
    assignee_id?: string
}